support widgets
divar-ir/kenar-api pull request #8
Opened 2024-07-01 10:30 UTC by nastaran78

Widget support in addon creation:
    DescriptionRow,
    EvaluationRow,
    EventRow,
    GroupInfo,
    LegendTitleRow,
    ScoreRow,
    SelectorRow,
    SubtitleRow,
    TitleRow,
    WideButtonBar

2024-07-01 12:51 UTC, ehsundar requested changes

2024-07-01 12:51 UTC, ehsundar commented on kenar/models/widgets/description_row.py
> +    def serialize_model(self) -> dict:
به نظرم سریالایزبل و دیسریالایزبل لازمه اینترفیس باشن و هر ایمیج پیاده‌ش کنه

2024-07-01 12:51 UTC, ehsundar commented on kenar/models/widgets/description_row.py
> +        return cls.parse_obj(widget_data)
به طور کلی با این روش پیاده سازی موافق نیستم. لکن برای الان میتونیم جلو بریم تا بعد صریح بنویسیم

2024-07-01 12:51 UTC, ehsundar commented on kenar/models/addon.py
>  from enum import Enum
به نظرم پکیج مدلز یه لایه نست اضافی یه و میتونه محتواش منتقل بشه به کنار

2024-07-01 12:51 UTC, ehsundar commented on samples/sample_addon.py
> +from kenar.models.widgets.wide_button_bar import WideButtonBar
برای جلوگیری از این روش سخت ایمپورت و سرراست تر شدن اکسپورت شده ها، میتونی اینا رو توی init پکیج ویجت ایمپورت کنی و همه از اونجا ایمپورت کنن

2024-07-01 12:51 UTC, ehsundar commented on samples/sample_addon.py
> +        image_url='https://s100.divarcdn.com/static/images/open-platform/CVbl3wzcVeT4jQkZ_jXwCg.jpg',
میشه این رو عکسش رو هم آپلود کنی؟

2024-07-01 12:58 UTC, nastaran78 commented on kenar/models/widgets/description_row.py
> +    def serialize_model(self) -> dict:
یه تلاشی کردم اتفاقا - امنا چون هم ABC و هم BaseModel میاد متاکلاس رو تغییر میدن، نمیشد.
باز الان نگاه میکنم به جز ابسترکت انجامش بدم

2024-07-01 13:00 UTC, nastaran78 commented on kenar/models/widgets/description_row.py
> +        return cls.parse_obj(widget_data)
چرا موافق نیستی؟ معکوس شده ی serialize عه دقیقا. من از اینکه منطق دو جا هست ناراحتم. اما اینکه اینجا بیاییم explicit فیلد ها رو بذاریم ،مطمئن نیستم

2024-07-01 13:00 UTC, nastaran78 commented on kenar/models/addon.py
>  from enum import Enum
کلا مدل های پایدنتیک رو آوردم اینجا فقط addon نیست. بقیه رو هم میگی منتقل کنم؟

2024-07-01 13:01 UTC, nastaran78 commented on samples/sample_addon.py
> +        image_url='https://s100.divarcdn.com/static/images/open-platform/CVbl3wzcVeT4jQkZ_jXwCg.jpg',
خواستم هر بار توی تست این آپلوده انجام نشه ولی میتونم کامنت شده بذارم

2024-07-02 10:10 UTC, nastaran78 commented on samples/sample_addon.py
> +        image_url='https://s100.divarcdn.com/static/images/open-platform/CVbl3wzcVeT4jQkZ_jXwCg.jpg',
used 'logo' instead

2024-07-02 10:20 UTC, merged